[package]
name = "gmdns"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8"
bytes = "1"
bitfield-struct = "0.10"
tracing = "0.1"
socket2 = { version = "0.5.8", features = ["all"] }
tokio = { version = "1", features = ["time", "macros", "net", "sync", "rt"] }
tokio-util = { version = "0.7", features = ["rt"] }
dashmap = "6"
rand = "0.9"
futures = "0.3"
flume = "0.11.1"
thiserror = "2.0.12"

[dev-dependencies]
clap = { version = "4", features = ["derive"] }
tracing-subscriber = "0.3"

[[example]]
name = "query"
path = "examples/query.rs"

[[example]]
name = "discover"
path = "examples/discover.rs"
