[package]
name = "gmdns"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8"
bytes = "1"
bitfield-struct = "0.10"
tracing = "0.1"
tracing-subscriber = "0.3"
socket2 = { version = "0.5.8", features = ["all"] }
tokio = { version = "1", features = ["time", "macros", "net", "sync", "rt"] }
tokio-stream = "0.1.17"
clap = { version = "4", features = ["derive"] }
dashmap = "6"
rand = "0.9"
futures = "0.3"
flume = "0.11.1"
thiserror = "2.0.12"

[target.'cfg(target_os = "android")'.dependencies]
pnet = "0.35.0"

[target.'cfg(not(target_os = "android"))'.dependencies]
getifs = "0.3"

[[example]]
name = "query"
path = "examples/query.rs"

[[example]]
name = "discover"
path = "examples/discover.rs"
